### ISSUE TITLE
Consultas search breaks when you put an empty name and press ENTER

### ISSUE THREAD

**Issue by dan-albuquerque** [dan-albuquerque/Projeto-Banco-de-dados#3]
searchBar retorna um erro quando você não coloca nada na barra e aperta enter, provavelmente é alguma coisa do useState

![image](https://github.com/dan-albuquerque/Projeto-Banco-de-dados/assets/114592376/3bd18018-6a51-4ae2-8f2f-a7d1ff3c4a2d)

**Comment by CarlosAugustoP** [comment]
added a trim() js function, that will now see if theres actually something to send. 
![image](https://github.com/dan-albuquerque/Projeto-Banco-de-dados/assets/117591564/a3b45196-511b-49fa-b9c9-c3d9639282ee)
